#!/usr/bin/env python3
"""Generate deterministic, sanitized inventory views from version-tracker SQLite."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sqlite3
import stat
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit


_SENSITIVE_KEYS = (
    "access_key",
    "api_key",
    "apikey",
    "auth",
    "bearer",
    "cookie",
    "credential",
    "password",
    "private_key",
    "secret",
    "session",
    "token",
    "username",
)
_PUBLIC_REPOSITORY = re.compile(
    r"^[A-Za-z0-9](?:[A-Za-z0-9_.-]{0,62}[A-Za-z0-9])?/"
    r"[A-Za-z0-9](?:[A-Za-z0-9_.-]{0,98}[A-Za-z0-9])?$"
)
_PUBLIC_DOMAIN_PATH = re.compile(
    r"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}"
    r"(?:/[A-Za-z0-9._~-]+)*$",
    re.IGNORECASE,
)
_PUBLIC_ANDROID_ID = re.compile(r"^[A-Za-z0-9]+(?:\.[A-Za-z0-9_-]+){2,}$")
_PUBLIC_IOS_ID = re.compile(r"^(?:[0-9]+|[A-Za-z0-9]+(?:\.[A-Za-z0-9_-]+){2,})$")
_PUBLIC_PACKAGE = re.compile(
    r"^(?:npm:(?:@[a-z0-9][a-z0-9._-]*/)?|pypi:)[a-z0-9][a-z0-9._-]*$",
    re.IGNORECASE,
)
_PUBLIC_CONTAINER = re.compile(
    r"^[a-z0-9][a-z0-9._-]*(?:/[a-z0-9][a-z0-9._-]*)+$",
    re.IGNORECASE,
)


def _safe_url(value: str | None) -> str | None:
    if not value:
        return value
    try:
        parts = urlsplit(str(value))
        hostname = parts.hostname or ""
        if ":" in hostname:
            hostname = f"[{hostname}]"
        port = f":{parts.port}" if parts.port else ""
        path = "/[REDACTED]" if parts.path and parts.path != "/" else parts.path
        query = "[REDACTED]" if parts.query else ""
        return urlunsplit((parts.scheme, hostname + port, path, query, ""))
    except (TypeError, ValueError):
        return "[INVALID_URL]"


def _safe_source_identifier(
    value: str,
    source_type: str,
    check_method: str,
    vector_type: str,
    canonical_identifier: str,
) -> str:
    """Preserve only identifiers generated by a documented source context."""
    value = str(value)
    try:
        urlsplit(value)
    except (TypeError, ValueError):
        return "[REDACTED]"

    canonical = str(canonical_identifier)
    context = (vector_type, source_type, check_method)
    expected: set[str] = set()
    if vector_type == "github_repository" and _PUBLIC_REPOSITORY.fullmatch(canonical):
        if context == ("github_repository", "github_release", "latest_release"):
            expected.add(f"{canonical}-releases")
        elif context in {
            ("github_repository", "github", "latest_tag"),
        }:
            expected.add(f"{canonical}-tags")
    elif vector_type == "api" and _PUBLIC_DOMAIN_PATH.fullmatch(canonical):
        if context == ("api", "api", "json_path"):
            expected.update(
                {
                    f"{canonical}{path}"
                    for path in ("/version", "/api/version", "/health", "/status")
                }
            )
    elif vector_type == "android_app" and _PUBLIC_ANDROID_ID.fullmatch(canonical):
        if source_type == "android_store" and check_method in {
            "google_play_scrape",
            "play_store",
        }:
            expected.add(f"{canonical}-playstore")
    elif vector_type == "ios_app" and _PUBLIC_IOS_ID.fullmatch(canonical):
        if source_type == "ios_store" and check_method in {
            "app_store_lookup",
            "app_store",
        }:
            expected.add(f"{canonical}-appstore")
    elif vector_type == "package" and _PUBLIC_PACKAGE.fullmatch(canonical):
        if context == ("package", "package_registry", "registry_api"):
            ecosystem, package = canonical.split(":", 1)
            expected.update({canonical, f"{ecosystem}-{package}"})
    elif vector_type == "docker_image" and _PUBLIC_CONTAINER.fullmatch(canonical):
        if context == ("docker_image", "package_registry", "registry_api"):
            expected.add(f"docker-{canonical}")
    elif vector_type == "website" and _PUBLIC_DOMAIN_PATH.fullmatch(canonical):
        if context == ("website", "rss", "feed_parse"):
            expected.add(f"{canonical}-rss")

    if value in expected:
        return value
    return "[REDACTED]"


def _sanitize(value: Any, parent_key: str = "") -> Any:
    if isinstance(value, dict):
        result = {}
        for key, item in value.items():
            normalized = str(key).lower()
            if normalized == "headers" or any(term in normalized for term in _SENSITIVE_KEYS):
                result[key] = "[REDACTED]"
            elif "url" in normalized and isinstance(item, str):
                result[key] = _safe_url(item)
            else:
                result[key] = _sanitize(item, normalized)
        return result
    if isinstance(value, list):
        return [_sanitize(item, parent_key) for item in value]
    return value


def _parse_config(raw: str | None) -> dict[str, Any] | str:
    if not raw:
        return {}
    try:
        return _sanitize(json.loads(raw))
    except (json.JSONDecodeError, TypeError):
        return "[INVALID_JSON]"


def build_inventory_snapshot(db_path: str | Path, observed_at: str) -> dict[str, Any]:
    """Read one canonical inventory snapshot from *db_path*."""
    database_uri = Path(db_path).absolute().as_uri() + "?mode=ro"
    connection = sqlite3.connect(database_uri, uri=True)
    connection.row_factory = sqlite3.Row
    connection.execute("BEGIN")
    try:
        targets = [
            dict(row)
            for row in connection.execute(
                "SELECT * FROM target ORDER BY canonical_name, target_id"
            )
        ]
        assets = [
            dict(row)
            for row in connection.execute(
                """
                SELECT t.target_id, t.canonical_name AS target, t.target_status,
                       a.asset_id, a.vector_type, a.canonical_identifier,
                       a.display_name, a.environment, a.status AS asset_status,
                       a.discovery_method, a.discovery_source_url,
                       ta.relationship, ta.is_current
                FROM target AS t
                JOIN target_asset AS ta ON ta.target_id = t.target_id
                JOIN asset AS a ON a.asset_id = ta.asset_id
                ORDER BY a.canonical_identifier, a.vector_type,
                         t.canonical_name, a.asset_id
                """
            )
        ]
        version_sources = [
            dict(row)
            for row in connection.execute(
                """
                SELECT vs.version_source_id, vs.asset_id,
                       a.vector_type, a.canonical_identifier,
                       a.status AS asset_status, vs.source_type,
                       vs.source_identifier, vs.check_method, vs.source_url,
                       vs.config, vs.enabled, vs.check_interval,
                       vs.on_error_policy, vs.last_checked_at,
                       vs.last_success_at, vs.last_error_at,
                       vs.last_error_code, vs.consecutive_failures,
                       vs.next_check_at,
                       (SELECT cr.status
                          FROM check_run AS cr
                         WHERE cr.version_source_id = vs.version_source_id
                         ORDER BY cr.check_run_id DESC LIMIT 1) AS latest_run_status
                  FROM version_source AS vs
                  JOIN asset AS a ON a.asset_id = vs.asset_id
                 ORDER BY a.canonical_identifier, vs.version_source_id
                """
            )
        ]
        target_associations: dict[int, list[dict[str, Any]]] = {}
        for row in connection.execute(
            """
            SELECT ta.asset_id, t.target_id, t.canonical_name, t.target_status
              FROM target_asset AS ta
              JOIN target AS t ON t.target_id = ta.target_id
             WHERE ta.is_current = 1
             ORDER BY ta.asset_id, t.canonical_name, t.target_id
            """
        ):
            association = dict(row)
            asset_id = association.pop("asset_id")
            target_associations.setdefault(asset_id, []).append(association)
        scope_records = [
            dict(row)
            for row in connection.execute(
                """
                SELECT sr.scope_id, sr.asset_id, bp.external_handle,
                       bp.name AS program, bp.program_url, bp.policy_url,
                       bp.program_status, sr.asset_identifier, sr.asset_type,
                       sr.scope_status, sr.eligible_for_bounty,
                       sr.eligible_for_submission, sr.instruction,
                       sr.is_current, sr.verification_status
                  FROM scope_record AS sr
                  JOIN bug_bounty_program AS bp
                    ON bp.program_id = sr.program_id
                 WHERE sr.is_current = 1
                 ORDER BY bp.external_handle, sr.asset_identifier,
                          sr.asset_type, sr.scope_id
                """
            )
        ]
    finally:
        connection.close()

    targets = _sanitize(targets)
    assets = _sanitize(assets)
    for source in version_sources:
        source["source_identifier"] = _safe_source_identifier(
            source["source_identifier"],
            source["source_type"],
            source["check_method"],
            source["vector_type"],
            source["canonical_identifier"],
        )
        source["source_url"] = _safe_url(source["source_url"])
        source["config"] = _parse_config(source["config"])
        source["targets"] = target_associations.get(source["asset_id"], [])
    scope_records = _sanitize(scope_records)
    scheduled_sources = [
        source
        for source in version_sources
        if source["enabled"] == 1
        and source["asset_status"] == "active"
        and any(target["target_status"] == "active" for target in source["targets"])
    ]

    return {
        "observed_at": observed_at,
        "summary": {
            "targets_total": len(targets),
            "targets_active": sum(row["target_status"] == "active" for row in targets),
            "current_assets_on_active_targets": sum(
                row["target_status"] == "active"
                and row["is_current"] == 1
                and row["asset_status"] == "active"
                for row in assets
            ),
            "version_sources_total": len(version_sources),
            "version_sources_enabled": sum(
                source["enabled"] == 1 for source in version_sources
            ),
            "scheduled_sources": len(scheduled_sources),
            "scheduled_by_type": dict(
                sorted(Counter(source["source_type"] for source in scheduled_sources).items())
            ),
            "scheduled_by_method": dict(
                sorted(Counter(source["check_method"] for source in scheduled_sources).items())
            ),
            "scheduled_failures": sum(
                source["consecutive_failures"] > 0 for source in scheduled_sources
            ),
            "current_scope_records": len(scope_records),
        },
        "targets": targets,
        "assets": assets,
        "version_sources": version_sources,
        "scheduled_version_sources": scheduled_sources,
        "scope_records": scope_records,
    }


def render_json(snapshot: dict[str, Any]) -> str:
    return json.dumps(snapshot, indent=2, sort_keys=True) + "\n"


def _markdown_cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        value = json.dumps(value, sort_keys=True, separators=(",", ":"))
    return str(value).replace("|", "\\|").replace("\n", " ")


def _append_record_table(
    lines: list[str], title: str, records: list[dict[str, Any]]
) -> None:
    lines.extend(["", f"## {title}", ""])
    if not records:
        lines.append("_None._")
        return
    columns = sorted({key for record in records for key in record})
    lines.append("| " + " | ".join(columns) + " |")
    lines.append("| " + " | ".join("---" for _ in columns) + " |")
    for record in records:
        lines.append(
            "| "
            + " | ".join(_markdown_cell(record.get(column)) for column in columns)
            + " |"
        )


def render_markdown(snapshot: dict[str, Any]) -> str:
    lines = [
        "# Version Tracker Inventory",
        "",
        f"Observed at: `{snapshot['observed_at']}`",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
    ]
    for key, value in snapshot["summary"].items():
        label = key.replace("_", " ").capitalize()
        lines.append(f"| {label} | {_markdown_cell(value)} |")

    _append_record_table(lines, "Targets", snapshot["targets"])
    _append_record_table(lines, "Assets", snapshot["assets"])
    _append_record_table(lines, "Version sources", snapshot["version_sources"])
    _append_record_table(
        lines,
        "Scheduled version sources",
        snapshot["scheduled_version_sources"],
    )
    _append_record_table(lines, "Current scope", snapshot["scope_records"])
    return "\n".join(lines) + "\n"


def check_inventory(
    *,
    db_path: str | Path,
    json_path: str | Path,
    markdown_path: str | Path,
) -> list[str]:
    """Return the paths of inventory artifacts stale against current DB state."""
    json_path = Path(json_path)
    markdown_path = Path(markdown_path)
    stale: list[str] = []
    try:
        actual_markdown = markdown_path.read_text(encoding="utf-8")
    except OSError:
        actual_markdown = None
    try:
        actual_json = json.loads(json_path.read_text(encoding="utf-8"))
        observed_at = actual_json.get("observed_at", "")
    except (OSError, json.JSONDecodeError, AttributeError):
        actual_json = None
        observed_at = ""
    if not isinstance(observed_at, str) or not observed_at:
        timestamp_match = re.search(
            r"^Observed at: `([^`]+)`$", actual_markdown or "", re.MULTILINE
        )
        observed_at = timestamp_match.group(1) if timestamp_match else ""

    expected = build_inventory_snapshot(db_path, observed_at)
    if actual_json != expected:
        stale.append(str(json_path))
    if actual_markdown != render_markdown(expected):
        stale.append(str(markdown_path))
    return stale


def _stage_private(path: Path, content: str) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=destination.parent,
            prefix=".inventory.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary_name = temporary.name
            os.fchmod(temporary.fileno(), 0o600)
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
        staged = Path(temporary_name)
        temporary_name = None
        return staged
    finally:
        if temporary_name is not None:
            Path(temporary_name).unlink(missing_ok=True)


def _replace_private_pair(outputs: list[tuple[Path, str]]) -> None:
    destinations = [path for path, _ in outputs]
    resolved_destinations = [path.resolve(strict=False) for path in destinations]
    if len(set(resolved_destinations)) != len(resolved_destinations):
        raise ValueError("inventory output paths must be distinct")

    staged: dict[Path, Path] = {}
    backups: dict[Path, Path] = {}
    original_modes: dict[Path, int] = {}
    replaced: list[Path] = []
    try:
        for destination, content in outputs:
            staged[destination] = _stage_private(destination, content)
        for destination in destinations:
            if destination.exists():
                original_modes[destination] = stat.S_IMODE(destination.stat().st_mode)
                with tempfile.NamedTemporaryFile(
                    dir=destination.parent,
                    prefix=".inventory.backup.",
                    delete=False,
                ) as backup:
                    backup_path = Path(backup.name)
                backups[destination] = backup_path
                shutil.copyfile(destination, backup_path)
                backup_path.chmod(0o600)
        try:
            for destination in destinations:
                os.replace(staged[destination], destination)
                staged.pop(destination)
                replaced.append(destination)
        except BaseException:
            for destination in reversed(replaced):
                backup = backups.pop(destination, None)
                if backup is None:
                    destination.unlink(missing_ok=True)
                else:
                    os.replace(backup, destination)
                    destination.chmod(original_modes[destination])
            raise
    finally:
        for temporary in [*staged.values(), *backups.values()]:
            temporary.unlink(missing_ok=True)


def refresh_inventory(
    *,
    db_path: str | Path,
    json_path: str | Path,
    markdown_path: str | Path,
    observed_at: str,
) -> dict[str, Any]:
    """Callable integration hook: refresh both views from one DB snapshot."""
    snapshot = build_inventory_snapshot(db_path, observed_at)
    _replace_private_pair(
        [
            (Path(json_path), render_json(snapshot)),
            (Path(markdown_path), render_markdown(snapshot)),
        ]
    )
    return snapshot


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate or check deterministic sanitized inventory artifacts."
    )
    parser.add_argument("--db", required=True, help="SQLite database path")
    parser.add_argument("--json", required=True, help="JSON artifact path")
    parser.add_argument("--markdown", required=True, help="Markdown artifact path")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write both artifacts")
    mode.add_argument("--check", action="store_true", help="check both artifacts")
    parser.add_argument(
        "--observed-at",
        help="controlled observation timestamp (required with --write)",
    )
    args = parser.parse_args(argv)

    if args.write:
        if not args.observed_at:
            parser.error("--observed-at is required with --write")
        refresh_inventory(
            db_path=args.db,
            json_path=args.json,
            markdown_path=args.markdown,
            observed_at=args.observed_at,
        )
        print(f"wrote {args.json}")
        print(f"wrote {args.markdown}")
        return 0

    if args.observed_at:
        parser.error("--observed-at is only valid with --write")
    stale = check_inventory(
        db_path=args.db,
        json_path=args.json,
        markdown_path=args.markdown,
    )
    if stale:
        for path in stale:
            print(f"stale: {path}")
        return 1
    print("inventory is fresh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
